name: CI pipeline

on: 
#  push:
#    branches:
#      - '**'
#    tags-ignore:
#      - '**'
#
#  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: [windows-latest]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3        
        #with:
        #  vs-version: 16.9
        #  vswhere-path: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      - name: Build-x86
        run: |
          ver
          dir
          cd "C:\Program Files (x86)"
          dir
          type %0
        #    "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe" libPcapNgParser.sln  /p:configuration=Release /p:Platform=x86
        shell: cmd

      - name: Build-x86
        run: |
          msbuild aaa.sln
        shell: cmd
